### ISSUE TITLE
gkeepapi.exception.LoginException: ('BadAuthentication', None)

### ISSUE THREAD

**Issue by LucasLake** [flecmart/keep2todoist#38] opened 2023-09-19 21:06 UTC
I love Keep2Todoist! I've been using it for almost a year without any issues. 
Since last week, without performing any software updates, I'm getting the following error:
```
python3 app.py
2023-09-19 22:57:04 configManager-INFO: validating configuration with schema 'config.schema.yaml'
2023-09-19 22:57:04 configManager-INFO: schema validation passed 👍
2023-09-19 22:57:04 configManager-INFO: configuration validation passed 👍
2023-09-19 22:57:04 configManager-INFO: updated config: config.yaml
Traceback (most recent call last):
  File "/config/notebooks/keep2todoist/app/app.py", line 169, in <module>
    keep.login(configManager.config['google_username'], configManager.config['google_password'], device_id='3ee9002270d00157')
  File "/usr/local/lib/python3.11/dist-packages/gkeepapi/__init__.py", line 695, in login
    ret = auth.login(username, password, device_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gkeepapi/__init__.py", line 59, in login
    raise exception.LoginException(
gkeepapi.exception.LoginException: ('BadAuthentication', None)
```

I tried re-installing the packages, pulling a new version from Git, rebuilding Python, updating Python, restarting Jupyter, rebooting HomeAssistant (which runs Jupyter), changing the GKeepApi version to 0.13.6, creating a new Google App password, but unfortunately nothing works. Even putting a false password in config.yaml results in the same error. 

I have no idea what to try next. 

Can anybody be of any help?

**Comment by flecmart** [comment] 2023-09-19 21:27
Hey there,

Just a quick response without having the time to further investigate at the moment: Maybe related to #29?

If you have the chance to try the prebuilt docker image you can eliminate any version or dependency conflicts.

**Comment by LucasLake** [comment] 2023-09-22 11:42
Hey flecmart,

Apologies for the slow response. I had no experience with Docker so it took me a bit of time to set it up. 

Indeed, a Docker installation does solve the issue. Tnx! 
Dockers is more cumbersome for me though as I need to rent a separate small AWS server. 
Is there any possibility for a fix in Jupyter? My Jupyter runs on Home Assistant.

**Comment by flecmart** [comment] 2023-09-23 07:13
Hey again,

okay my guess is something changed in your home assistant environment then at some point. What are you using? HassOS? 

I think your issue is related to this: https://github.com/simon-weber/gpsoauth/issues/48#issuecomment-1690340572

Of course you can also make it work without docker allthough it might be complicated depending on your environment. It needs a certain version of openssl installed and you need to make sure that you have the current `requirements.txt` from this repo using `urllib3<2`.

**Comment by flecmart** [comment] 2023-10-04 12:00
I improved the auth process to google with release https://github.com/flecmart/keep2todoist/releases/tag/v1.5.0
I close the issue because I could not reproduce the problem within my dev environment.

**Closed by flecmart** 2023-10-04 12:00 UTC
